// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD475wfEGrv_c-8dsSjv9AIYl0TWmJmSXo',
    appId: '1:667911716229:web:77244d7a0ee71ac49cd8ec',
    messagingSenderId: '667911716229',
    projectId: 'login-cc5ea',
    authDomain: 'login-cc5ea.firebaseapp.com',
    storageBucket: 'login-cc5ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYOlaYqpnuRQFyEEdWAgEdvtZmk_4zW0',
    appId: '1:667911716229:android:880063db057161c59cd8ec',
    messagingSenderId: '667911716229',
    projectId: 'login-cc5ea',
    storageBucket: 'login-cc5ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8pggM7_kWvc5izjNsag9utk-lQ8L6zA',
    appId: '1:667911716229:ios:6f7f72891abfb4169cd8ec',
    messagingSenderId: '667911716229',
    projectId: 'login-cc5ea',
    storageBucket: 'login-cc5ea.firebasestorage.app',
    iosBundleId: 'com.example.shopgram',
  );
}
